# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
