# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-04 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_linkedinprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='checker',
        ),
    ]
