# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-29 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_exceptld'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcepTld',
            new_name='ExceptTld',
        ),
    ]
